name: Build Linux and macOS Installers

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        lf: true
        
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: "3.10"
        miniconda-version: "latest"
        auto-activate-base: true  # Importante!
        activate-environment: builder
        channels: conda-forge,defaults
        channel-priority: strict
        
    - name: Install constructor
      shell: bash -l {0}  # Usar shell login
      run: |
        conda install -c conda-forge constructor=3.11.3 -y
        which constructor  # Verificar ubicaci贸n
        constructor --version  # Verificar versi贸n
        
    - name: Verify installation
      shell: bash -l {0}
      run: |
        conda list constructor
        python -c "import constructor; print(constructor.__version__)"
        
    - name: Build Linux installer
      shell: bash -l {0}
      run: |
        constructor --platform linux-64 --verbose .
        
    - name: Upload Linux installer
      uses: actions/upload-artifact@v4
      with:
        name: ISQ_Suite_Linux_Installer
        path: dist/*.sh

  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        lf: true
        
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: "3.10"
        miniconda-version: "latest"
        auto-activate-base: true  # Importante!
        activate-environment: builder
        channels: conda-forge,defaults
        channel-priority: strict
        
    - name: Install constructor
      shell: bash -l {0}  # Usar shell login
      run: |
        conda install -c conda-forge constructor=3.11.3 -y
        which constructor  # Verificar ubicaci贸n
        constructor --version  # Verificar versi贸n
        
    - name: Verify installation
      shell: bash -l {0}
      run: |
        conda list constructor
        python -c "import constructor; print(constructor.__version__)"
        
    - name: Build macOS installer
      shell: bash -l {0}
      run: |
        constructor --platform osx-64 --verbose .
        
    - name: Upload macOS installer
      uses: actions/upload-artifact@v4
      with:
        name: ISQ_Suite_macOS_Installer
        path: dist/*.pkg
