name: Build ISQ Suite

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nuitka

    - name: Compile iNMR
      run: |
        nuitka src/suite/apps/iNMR/maini.py --standalone --enable-plugin=tk-inter --output-dir=build/iNMR

    - name: Compile sNMR
      run: |
        nuitka src/suite/apps/sNMR/mains.py --standalone --enable-plugin=tk-inter --output-dir=build/sNMR

    - name: Compile qNMR
      run: |
        nuitka src/suite/apps/qNMR/mainq.py --standalone --enable-plugin=tk-inter --output-dir=build/qNMR

    - name: Compile launcher
      run: |
        nuitka src/suite/launcher.py --standalone --enable-plugin=tk-inter --output-dir=build/launcher

    - name: Prepare final distribution folder
      run: |
        mkdir build\ISQ_Suite.dist
        # Copiar ejecutables
        copy build\iNMR\maini.exe build\ISQ_Suite.dist\iNMR.exe
        copy build\sNMR\mains.exe build\ISQ_Suite.dist\sNMR.exe
        copy build\qNMR\mainq.exe build\ISQ_Suite.dist\qNMR.exe
        copy build\launcher\launcher.exe build\ISQ_Suite.dist\launcher.exe
        # Copiar recursos (íconos)
        mkdir build\ISQ_Suite.dist\icons
        copy src\resources\icons\*.ico build\ISQ_Suite.dist\icons\

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: ISQ_Suite
        path: build/ISQ_Suite.dist/


