name: Build ISQ Suite Launcher

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nuitka

      - name: Build ISQ Suite Launcher
        run: >
          nuitka src/suite/launcher.py
            --standalone
            --enable-plugin=tk-inter
            --output-dir=build
            --output-filename=ISQ_Suite
            --include-data-dir=resources=resources

      - name: Upload ISQ Suite Executable
        uses: actions/upload-artifact@v4
        with:
          name: ISQ_Suite
          path: build/ISQ_Suite.dist/

