name: Build Linux Installer

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        auto-activate-base: true
        channels: conda-forge,defaults
        channel-priority: strict
        
    - name: Install Python and dependencies
      run: |
        conda install python=3.10 -y
        pip install ruamel.yaml
        
    - name: Install constructor from source
      run: |
        # Instalar versión específica desde GitHub
        git clone https://github.com/conda/constructor.git
        cd constructor
        git checkout 3.11.3
        pip install .
        cd ..
        
    - name: Verify installation
      run: |
        echo "Python version: $(python --version)"
        echo "Constructor path: $(which constructor)"
        constructor --version
        python -c "import constructor; print(f'Constructor module version: {constructor.__version__}')"
        
    - name: Build installer
      run: |
        # Usar un construct.yaml simplificado
        echo "name: Test_Installer" > minimal.yaml
        echo "version: 1.0.0" >> minimal.yaml
        echo "channels:" >> minimal.yaml
        echo "  - conda-forge" >> minimal.yaml
        echo "specs:" >> minimal.yaml
        echo "  - python=3.10" >> minimal.yaml
        echo "  - numpy" >> minimal.yaml
        
        constructor --platform linux-64 minimal.yaml
        
    - name: Build main installer
      run: |
        # Construir con tu configuración principal
        constructor --platform linux-64 --verbose .
        
    - name: Upload installer
      uses: actions/upload-artifact@v4
      with:
        name: ISQ_Suite_Linux_Installer
        path: dist/*.sh
