name: Build Linux Installer

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        lf: true
        
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: "3.10"
        miniconda-version: "latest"
        auto-activate-base: true
        activate-environment: builder
        channels: conda-forge,defaults
        channel-priority: strict
        
    - name: Install constructor
      shell: bash -l {0}
      run: |
        conda install -n base -c conda-forge constructor=3.11.3 -y
        echo "===== Constructor Info ====="
        which constructor
        constructor --version
        python -c "import constructor; print(f'Module version: {constructor.__version__}'); print(f'Module path: {constructor.__file__}')"
        
    - name: Debug environment
      run: |
        echo "===== Environment Variables ====="
        env | sort
        echo "===== Conda Info ====="
        conda info
        conda list
        echo "===== Python Path ====="
        python -c "import sys; print(sys.path)"
        
    - name: Create test config
      run: |
        echo "name: Test_Installer" > test.yaml
        echo "version: 1.0.0" >> test.yaml
        echo "channels:" >> test.yaml
        echo "  - conda-forge" >> test.yaml
        echo "specs:" >> test.yaml
        echo "  - python=3.10" >> test.yaml
        echo "  - numpy" >> test.yaml
        
    - name: Test minimal build
      run: |
        constructor --platform linux-64 --verbose test.yaml
        
    - name: Build main installer
      run: |
        constructor --platform linux-64 --verbose .
        
    - name: Upload installer
      uses: actions/upload-artifact@v4
      with:
        name: ISQ_Suite_Linux_Installer
        path: dist/*.sh
