name: Build Linux and macOS Installers

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        lf: true  # Usar terminadores de línea Unix
        
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: "3.10"
        miniconda-version: "latest"
        activate-environment: builder
        channels: conda-forge,defaults
        channel-priority: strict
        
    - name: Install constructor
      run: |
        conda install -c conda-forge constructor=3.11.3 -y
        constructor --version
        
    - name: Build Linux installer
      run: |
        constructor --platform linux-64 --verbose .
        
    - name: Upload Linux installer
      uses: actions/upload-artifact@v4
      with:
        name: Linux_Installer
        path: dist/*.sh

  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        lf: true
        
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: "3.10"
        miniconda-version: "latest"
        activate-environment: builder
        channels: conda-forge,defaults
        channel-priority: strict
        
    - name: Install constructor
      run: |
        conda install -c conda-forge constructor=3.11.3 -y
        constructor --version
        
    - name: Build macOS installer
      run: |
        constructor --platform osx-64 --verbose .
        
    - name: Upload macOS installer
      uses: actions/upload-artifact@v4
      with:
        name: macOS_Installer
        path: dist/*.pkg
