name: Build ISQ Suite Installer

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-windows-installer:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: "3.10"
        miniconda-version: "latest"
        auto-update-conda: true
        activate-environment: "isq-suite"
        
    - name: Install dependencies
      run: |
        conda install -c conda-forge conda-build -y
        pip install ruamel.yaml
        conda list
        
    - name: Install Constructor
      run: pip install git+https://github.com/conda/constructor@main
        
    - name: Install conda-standalone
      run: |
        $condaUrl = "https://github.com/conda/conda-standalone/releases/download/24.5.0-0/conda-win-64.exe"
        Invoke-WebRequest -Uri $condaUrl -OutFile conda.exe
        if (-not (Test-Path -Path "conda.exe")) {
            Write-Error "Failed to download conda-standalone"
            exit 1
        }
        echo "Conda standalone downloaded"
        
    - name: Validate project structure
      run: |
        python -c "import os; assert os.path.exists('src/suite/launcher.py'), 'ERROR: No se encuentra launcher.py'"
        python -c "import os; assert os.path.exists('resources/icons/'), 'ERROR: No se encuentra la carpeta de íconos'"
        python -c "import os; assert os.path.exists('construct.yaml'), 'ERROR: No se encuentra construct.yaml'"
        
    - name: Test imports
      run: |
        conda create -n test_env python=3.10 -y
        conda activate test_env
        pip install -r requirements.txt
        pip install -e .
        
        # Pruebas de importación
        python -c "import suite; print('Módulo suite importado correctamente')"
        python -c "import suite.launcher; print('Módulo launcher importado')"
        python -c "import suite.apps.inmr.maini; print('Módulo iNMR importado')"
        python -c "import suite.apps.qnmr.mainq; print('Módulo qNMR importado')"
        python -c "import suite.apps.snmr.mains; print('Módulo sNMR importado')"
        
    - name: Build installer
      run: |
        constructor --conda-exe "$(pwd)\conda.exe" --platform win-64 .
      
    - name: Save installer artifact
      uses: actions/upload-artifact@v4
      with:
        name: ISQ_Suite_Installer
        path: output/*.exe
