name: Build ISQ Suite Installer

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-windows-installer:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: "3.10"
        miniconda-version: "latest"
        auto-update-conda: true
        activate-environment: "isq-suite"
        
    - name: Install dependencies
      run: |
        conda install -c conda-forge conda-build -y
        pip install ruamel.yaml
        conda list
        
    - name: Install Constructor
      run: pip install git+https://github.com/conda/constructor@main
        
    - name: Validate project structure
      run: |
        python -c "import os; assert os.path.exists('src/suite/launcher.py'), 'ERROR: No se encuentra launcher.py'"
        python -c "import os; assert os.path.exists('resources/icons/'), 'ERROR: No se encuentra la carpeta de íconos'"
        python -c "import os; assert os.path.exists('construct.yaml'), 'ERROR: No se encuentra construct.yaml'"
        python -c "import os; assert os.path.exists('meta.yaml'), 'ERROR: No se encuentra meta.yaml'"
        
    - name: Test imports
      run: |
        conda create -n test_env python=3.10 -y
        conda activate test_env
        pip install -e .
        
         # Verificar que los módulos existen
        python -c "import suite; print('[OK] Módulo suite importado correctamente')"
        python -c "import suite.apps.inmr; print('[OK] Módulo inmr importado correctamente')"
        python -c "import suite.apps.qnmr; print('[OK] Módulo qnmr importado correctamente')"
        python -c "import suite.apps.snmr; print('[OK] Módulo snmr importado correctamente')"
    
        # Verificar puntos de entrada
        python -c "from suite.launcher import SuiteApp; print('[OK] Clase LauncherApp disponible')"
        python -c "from suite.apps.inmr.maini import MainApp; print('[OK] iNMR importado')"
        python -c "from suite.apps.qnmr.mainq import QuantifyApp; print('[OK] qNMR importado')"
        python -c "from suite.apps.snmr.mains import ScalingApp; print('[OK] sNMR importado')"
        
    - name: Build installer
      run: constructor --platform win-64 .
      
    - name: Save installer artifact
      uses: actions/upload-artifact@v4
      with:
        name: ISQ_Suite_Installer
        path: output/*.exe
