name: Build ISQ Suite Installer

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-windows-installer:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: "3.10"
        activate-environment: constructor-env
        auto-activate-base: false
        channels: conda-forge,defaults
        
    - name: Install latest constructor
      shell: bash -l {0}
      run: |
        pip install --upgrade "constructor>=3.7.0"
        constructor --version
        
    - name: Install project dependencies
      run: |
        # Instalar dependencias que Constructor necesita para empaquetar
        pip install -r requirements.txt
        
    - name: Build installer
      run: |
        constructor --verbose --platform win-64 .
        
    - name: Upload installer
      uses: actions/upload-artifact@v4
      with:
        name: ISQ_Suite_Installer
        path: dist/*.exe  # Ruta corregida
