name: Build ISQ Suite Installer

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-windows-installer:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.10
        activate-environment: isq-build
        auto-activate-base: false
        channels: conda-forge,defaults
        
    - name: Install constructor
      shell: bash -l {0}  # Important for conda activation
      run: |
        conda install -c conda-forge constructor -y
        
    - name: Install project dependencies
      shell: bash -l {0}
      run: |
        # Instalar dependencias que Constructor necesita para empaquetar
        pip install -r requirements.txt
        
    - name: Build installer
      shell: bash -l {0}
      run: |
        constructor --platform win-64 .
        
    - name: Upload installer
      uses: actions/upload-artifact@v4
      with:
        name: ISQ_Suite_Installer
        path: dist/*.exe  # Ruta corregida
