name: Build ISQ Suite Installer

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-windows-installer:
    timeout-minutes: 45
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        lf: true  # Forzar terminadores de línea Unix
        
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: "3.10"
        miniconda-version: "latest"
        auto-update-conda: true
        activate-environment: build-env
        channels: conda-forge,defaults
        
    - name: Install constructor
      shell: bash -l {0}
      run: |
        conda install -c conda-forge constructor=3.11.3 -y
        constructor --version
        
    - name: Validate environment
      shell: bash -l {0}
      run: |
        conda list
        python -c "import sys; print(sys.executable)"
        python -c "import constructor; print(f'Constructor {constructor.__version__} at {constructor.__file__}')"
        
    - name: Build installer
      shell: bash -l {0}
      run: |
        # Crear copia de seguridad
        cp construct.yaml construct-original.yaml
        
        # Convertir a formato Unix
        dos2unix construct.yaml || true
        
        # Ejecutar constructor
        constructor --verbose --platform win-64 .
        
    - name: Save artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ISQ_Suite_Installer
        path: dist/*.exe
